config_route: notificacion_app_config
menu:
    notificacion:
        title: Notificacion
        type: toggle
        icon: 'mdi mdi-view-quilt'
        includes: notificacion
        children:
#            home:
#                title: 'Notificacion Homepage'
#                type: link
#                state: notificacion.homepage
            tiemporeal:
                title: Notificaciones en tiempo real
                type: link
                state: notificacion.tiemporeal
            correo:
                title: Correos
                type: link
                state: notificacion.correo
            bandejaentrada:
                title: Bandeja de notificaciones
                type: link
                state: bandejaentrada
