notificacion_ajax:
    path:     /notificaciones/security-token
    defaults: { _controller: NotificacionBundle:Notificacion:securityToken }
    methods: ["GET"]
    options:
        expose: true

controlador_notifi_view:
    resource: "@NotificacionBundle/Controller"
    type: annotation

notification_users:
    defaults: {_controller: NotificacionBundle:Notificacion:getUsers}
    methods: ["GET"]
    path: /notification_users
    options:
            expose: true

notification_roles:
    defaults: {_controller: NotificacionBundle:Notificacion:getRoles}
    methods: ["GET"]
    path: /notification_roles
    options:
            expose: true

notTest:
    defaults: {_controller: NotificacionBundle:Notificacion:index}
    path: /notificacionbundle/testview
    options:
                expose: true