notificacion_homepage:
    path:     /notificaciones
    defaults: { _controller: NotificacionBundle:Default:index }

notificacion_ajax:
    path:     /notificaciones/security-token
    defaults: { _controller: NotificacionBundle:Default:securityToken }
    methods: ["GET"]

#notificacion_get:
#    path: /notificacion
#    defaults: {_controller: NotificacionBundle:Default:getNotifListAdmin}
#    methods: ["GET"]
#
#notificacion_get_by_id:
#    path: /notificacion/{idNotif}
#    defaults: {_controller: NotificacionBundle:Default:getNotifById}
#    methods: ["GET"]
#
#notificacion_add:
#    path: /notificacion
#    defaults: {_controller: NotificacionBundle:Default:addNotif}
#    methods: ["POST"]
#
#notificacion_mod:
#    path: /notificacion/{idNotif}
#    defaults: {_controller: NotificacionBundle:Default:modNotif}
#    methods: ["PUT"]
#
#notificacion_del:
#    path: /notificacion/{idNotif}
#    defaults: {_controller: NotificacionBundle:Default:delNotif}
#    methods: ["DELETE"]

controlador_notifi_view:
    resource: @NotificacionBundle/Controller/
    type: annotation

notification_users:
    defaults: {_controller: NotificacionBundle:Notificacion:getUsers}
    methods: ["GET"]
    path: /notification_users
    options:
            expose: true

notification_roles:
    defaults: {_controller: NotificacionBundle:Notificacion:getRoles}
    methods: ["GET"]
    path: /notification_roles
    options:
            expose: true