notificacion_homepage:
    path:     /notificaciones
    defaults: { _controller: NotificacionBundle:Default:index }

notificacion_ajax:
    path:     /notificaciones/security-token
    defaults: { _controller: NotificacionBundle:Default:securityToken }
    methods: ["GET"]
