<?php

namespace UCI\Boson\NotificacionBundle\Entity;

/**
 * NotificacionRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class NotificacionRepository extends \Doctrine\ORM\EntityRepository
{
}
