<?php

namespace UCI\Boson\NotificacionBundle\Entity;

/**
 * TipoNotificacionRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class TipoNotificacionRepository extends \Doctrine\ORM\EntityRepository
{
}
